site_name: SmartDelivery Documentation

theme:
  name: material
  features:
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.highlight

extra_javascript:
  - https://unpkg.com/mermaid@11.4.1/dist/mermaid.min.js